/**
 * OllamaService.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Communicates with locally running Ollama LLM endpoint (default http://localhost:11434).
 * Fetches available models and handles streaming NDJSON generation.
 * Includes fallback simulator for offline execution / testing.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export class OllamaService {
  /**
   * Fetch available models from local Ollama instance.
   * @param {string} hostUrl
   * @returns {Promise<string[]>}
   */
  async listModels(hostUrl) {
    const res = await fetch(`${hostUrl}/api/tags`);
    if (!res.ok) {
      throw new Error(`Ollama connection status error: ${res.statusText}`);
    }
    const data = await res.json();
    return (data.models ?? []).map(m => m.name);
  }

  /**
   * Stream prediction generated by local LLM.
   * @param {string} hostUrl
   * @param {string} modelName
   * @param {string} promptText
   * @param {(chunk: string) => void} onChunk
   * @returns {Promise<string>} Full response text
   */
  async predictSeismicRupture(hostUrl, modelName, promptText, onChunk) {
    const response = await fetch(`${hostUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: modelName,
        prompt: promptText,
        stream: true
      })
    });

    if (!response.ok) {
      throw new Error(`Ollama generation status error: ${response.statusText}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    let fullText = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop(); // save remaining fragment

      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const parsed = JSON.parse(line);
          if (parsed.response) {
            fullText += parsed.response;
            onChunk(parsed.response);
          }
        } catch (e) {
          console.warn('[OllamaService] Failed to parse line:', line, e);
        }
      }
    }

    return fullText;
  }

  /**
   * Simulate a high-fidelity streaming generation for offline testing.
   * @param {(chunk: string) => void} onChunk
   * @returns {Promise<string>} Full response text
   */
  async generateMockPrediction(onChunk) {
    const textBlocks = [
      "[GFM-LLM DEEP PREDICTION SYSTEM // MULTI-SCENARIO GEODYNAMIC ACCURACY MODE]\n",
      "[MODEL]: Gemma 2B (Geophysical Fine-Tuned Epoch 4)\n",
      "[STATUS]: Critical strain saturation matched near Sarangani margin\n\n",
      "PHYSICAL SYSTEM LOGS:\n",
      "----------------------------------------\n",
      "- Integrated Precursor Lock-up : 94.2% seismic coupling\n",
      "- Target Fault Junction        : Cotabato Trench Subduction Complex\n",
      "- Calculated Stress Shift      : +1.8 bars (Threshold exceeded)\n",
      "- Active Thermal Precursors    : Mayon (Alert Level 3) active emissions indicating moderate magma convection\n\n",
      "FORECAST AND RUPTURE POSSIBILITY SCENARIOS:\n",
      "----------------------------------------\n",
      "SCENARIO A: Thrust Megashock (Primary Probability - 72%)\n",
      "  - Rupture Segment : Cotabato Trench Thrust Interface\n",
      "  - Coordinates     : 5.50° N, 125.00° E (Offshore Sarangani)\n",
      "  - Est. Magnitude  : Mw 7.6\n",
      "  - Ground Motion   : Max PGA modeled at 0.68g in General Santos City. Severe soil liquefaction expected near Silway delta.\n",
      "  - Tsunami Vector  : Significant wave propagation modeled for Sarangani Bay and Davao Gulf (2-4m height envelopes).\n\n",
      "SCENARIO B: Strike-Slip Reactivation (Secondary Probability - 21%)\n",
      "  - Rupture Segment : Central Mindanao Fault System (Southern Extension)\n",
      "  - Coordinates     : 6.22° N, 124.85° E (Maasim Foothills)\n",
      "  - Est. Magnitude  : Mw 7.2\n",
      "  - Ground Motion   : PGA modeled at 0.45g. Landslide risk flagged for Maasim highlands. Moderate road blocks on regional highway.\n\n",
      "SCENARIO C: Pull-Apart Basin Opening (Tertiary Probability - 7%)\n",
      "  - Rupture Segment : Sarangani Bay Pull-Apart Graben Splay\n",
      "  - Coordinates     : 5.95° N, 125.20° E (Sarangani Bay basin)\n",
      "  - Est. Magnitude  : Mw 6.5\n",
      "  - Ground Motion   : PGA modeled at 0.30g in GenSan. Underwater landslide risk, local harbor displacement.\n\n",
      "EMERGENCY COMMAND TRIACTION:\n",
      "----------------------------------------\n",
      "1. Activate emergency alarms and dispatch structural assessment teams to General Santos port and bridge networks.\n",
      "2. Place tsunami warning systems on high alert for coastal Maasim and Davao Gulf sectors.\n",
      "3. Spin up loopback backup servers to maintain communications during power grid drops.\n\n",
      "COORDINATES: 5.50, 125.00"
    ];

    let fullText = "";
    for (const block of textBlocks) {
      const words = block.split(/(\s+)/);
      for (const word of words) {
        if (!word) continue;
        fullText += word;
        onChunk(word);
        // Delay to simulate streaming
        await new Promise(resolve => setTimeout(resolve, 15 + Math.random() * 25));
      }
    }

    return fullText;
  }
}
